# This is a basic workflow to help you get started with Actions

name: readme2tex-action
author: amichuda
description: GH action that automatically builds every .tex.md file in the repo
branding:
  icon: "dollar-sign"
  color: "green"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: "composite"
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install pdflatex and rename
      run: sudo apt install texlive-latex-base rename
      shell: bash
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install readme2tex
      shell: bash
    - name: Build readmes
      run: |
        find . -type f -name 'README.md' -execdir python3 -m readme2tex --readme {} --nocdn --output "{}" \;
      shell: bash
    - name: Commit the built files
      run: |
        git config --global user.name 'Readme2Tex Bot'
        git config --global user.email '<>'
        git diff --quiet || (git add . && git commit -m "Built the .tex.md files")
        git push
      shell: bash
